/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CONTAS_H_RPCGEN
#define _CONTAS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct intValoresStr {
	int a;
	int b;
};
typedef struct intValoresStr intValoresStr;

typedef intValoresStr intValores;

#define CONTASPROG 0x289ABCDE
#define CONTASVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define somar 1
extern  int * somar_1(intValores *, CLIENT *);
extern  int * somar_1_svc(intValores *, struct svc_req *);
#define subtrair 2
extern  int * subtrair_1(intValores *, CLIENT *);
extern  int * subtrair_1_svc(intValores *, struct svc_req *);
#define multiplicar 3
extern  int * multiplicar_1(intValores *, CLIENT *);
extern  int * multiplicar_1_svc(intValores *, struct svc_req *);
#define dividir 4
extern  int * dividir_1(intValores *, CLIENT *);
extern  int * dividir_1_svc(intValores *, struct svc_req *);
extern int contasprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define somar 1
extern  int * somar_1();
extern  int * somar_1_svc();
#define subtrair 2
extern  int * subtrair_1();
extern  int * subtrair_1_svc();
#define multiplicar 3
extern  int * multiplicar_1();
extern  int * multiplicar_1_svc();
#define dividir 4
extern  int * dividir_1();
extern  int * dividir_1_svc();
extern int contasprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_intValoresStr (XDR *, intValoresStr*);
extern  bool_t xdr_intValores (XDR *, intValores*);

#else /* K&R C */
extern bool_t xdr_intValoresStr ();
extern bool_t xdr_intValores ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CONTAS_H_RPCGEN */
